<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="exam081207">
    <groups>
      <group name="tests.math">
        <method signature="testNGDemo.NumberUtilsTest.test()" name="test" class="testNGDemo.NumberUtilsTest"/>
      </group>
    </groups>
    <test name="testNGDemo.NumberUtilsTest">
      <class name="testNGDemo.NumberUtilsTest">
        <test-method status="PASS" signature="test()" name="test" duration-ms="78" started-at="2008-12-30T23:12:07Z" finished-at="2008-12-30T23:12:07Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[multiple points]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.lang.Double.valueOf(Unknown Source)
	at org.apache.commons.lang.math.NumberUtils.createDouble(NumberUtils.java:596)
	at testNGDemo.NumberUtilsTest.test(NumberUtilsTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:73)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:124)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
